name: ${project.name}
author: bmlzootown
version: ${project.version}
main: ml.bmlzootown.NameColors
depends: [LuckPerms]
api-version: 1.14
commands:
     namecolor:
          description: /namecolor [rank]
          aliases: [namec, ncolor, nc]