name: NameColors
author: bmlzootown
version: 2.0.0
main: ml.bmlzootown.NameColors
depends: [LuckPerms]
api-version: 1.13
commands:
     namecolor:
          description: /namecolor [rank]
          aliases: [namec, ncolor, nc]