name: ${project.name}
author: bmlzootown
version: ${project.version}
main: ml.bmlzootown.NameColors
depends: [LuckPerms]
api-version: 1.15
commands:
     namecolors:
          description: /namecolors [rank]
          aliases: [namec, ncolor, nc, namecs, ncolors, ncs]